T_language = {
	de: {
	  	wrapper: 			"Moderatoren-Forum",
		username: 			"Benutzername",
		ip_adresse: 		"IP-Adresse",
		manageuser: 		"User verwalten",
		mod_panel: 			"Mod Panel",
		close: 				"schließen",
		warnings_user: 		"Alle Verwarnungen",
		warn_user: 			"Verwarnen",
		ips: 				"IP\'s",
		adminSite_text: 	"Adminseite",
		pm_limit_changer: 	"PM-Limit-Changer",
		send_mail: 			"E-Mail schreiben",
		reply_forum: 		"Antworten",
		reply_magazin:	 	"Antworten",
		quote: 				"Zitat",
		default_text: 		"Standardtexte",
		forum: 				"neue-beitraege",
		userSearch: 		"userSearch",
		word_filter: 		"Wortfilter Treffer aktiviert",
		word_filter_match: 	"Treffer",
		deleted_user: 		"Gelöschter Account",
		trash_move: 		"Thread in den Papierkorb verschieben?",
		reason_move: 		"Thread ist im Korb! Willst du einen Grund eingeben? Titel ist der Standardtext",
		thread_close: 		"Thread schon geschlossen!",
		registration:		"Registrierung ",
		yes: 				"JA",
		no: 				"NEIN",
		okay: 				"Okay",
		search:				"suche",
		no_reply: 			"keinen Grund angeben"
	},
	br: {
		wrapper: 			"Painel de Moderadores do AndroidPIT",
		username: 			"Nome de usuário",
		ip_adresse: 		"Endereço IP",
		manageuser: 		"Gerenciar usuário",
		mod_panel: 			"Mod Panel",
		close: 				"Fechar",
		warnings_user: 		"todas as advertências",
		warn_user: 			"advertências",
		ips: 				"IP\'s",
		adminSite_text: 	"Admin site",
		pm_limit_changer: 	"PM limite interruptor",
		send_mail: 			"mail enviar",
		reply_forum: 		"Responder",
		reply_magazin:	 	"Responder",
		quote: 				"Citar",
		default_text: 		"Standard text",
		forum: 				"recente",
		userSearch: 		"userSearch",
		word_filter: 		"Word filters Results enabled",
		word_filter_match: 	"Result",
		deleted_user: 		"Desativado Account",
		trash_move: 		"mover para a lixeira",
		reason_move: 		"Lista está no cesto! Quer entrar um motivo? O título é o texto padrão",
		thread_close: 		"Thread já fechada!",
		registration:		"Cadastro ",
		yes: 				"Sim",
		no: 				"não",
		okay: 				"ok",
		search:				"Pesquisar",
		no_reply: 			"especifique nenhuma razão"
	}
}
