T_language = {
	de: {},
	br: {},
	com: {},
	default: {
		wrapper: "",
		username: "",
		ip_adresse: "",
		manageuser: "",
		mod_panel: "",
		close: "",
		warnings_user: "",
		warn_user: "",
		ips: "",
		adminSite_text: "",
		pm_limit_changer: "",
		send_mail: "",
		reply_forum: "",
		reply_magazin: "",
		quote: "",
		default_text: "",
		forum: "",
		userSearch: "",
		word_filter: "",
		word_filter_match: "",
		deleted_user: "",
		trash_move: "",
		reason_move: "",
		thread_close: "",
		registration: " ",
		yes: "",
		no: "",
		okay: "",
		search:	"",
		no_reply: ""
	}
}
